<# first run
$folders = @(
    "N:\3m.BUF",
    "N:\3m.CHI",
    "N:\Abbott.chi",
    "N:\Abbvie.CHI",
    "N:\AK_STEEL.ASH",
    "N:\AK_STEEL.ASH",
    "N:\Akzonoble.CHI",
    "N:\Althoff_industr.CHI",
    "N:\Altivia.ASH",
    "N:\Amer_elect_pwr.CLE",
    "N:\AMG Vanadium",
    "N:\Anheuser_Busch.CHI",
    "N:\Applied Metals.CLE",
    "N:\Arcelor_mittal",
    "N:\Arcelor_mittal.CHI",
    "N:\Army_contract.CHI",
    "N:\Ashland_chemical.ASH",
    "N:\Atlantic_Power.CHI",
    "N:\Aurubis.BUF",
    "N:\Aux_sable.CHI",
    "N:\Avery_dennison.CLE",
    "N:\AveXis_inc.CHI",
    "N:\B&G Foods.CHI",
    "N:\Baker Hughes",
    "N:\Baker_petrolite.CHI",
    "N:\Barry_Callebaut.CHI",
    "N:\Beyond_meat.CHI",
    "N:\BHE GT&S LLC",
    "N:\Big_river_steel.CLE",
    "N:\Bimbo Bakeries USA",
    "N:\Bio-Cat_Mico.CHI",
    "N:\BioMADE",
    "N:\Biourja.CHI",
    "N:\Blommer.CHI",
    "N:\Boyd_CY_Court.ASH",
    "N:\BP_OIL.CLE",
    "N:\Bp_research.CHI",
    "N:\Brandenburg_Ind.CHI",
    "N:\Brightmark_Eng",
    "N:\Bunge North Ame.CHI",
    "N:\BWX_Tech.CLE",
    "N:\Capchem Technology USA",
    "N:\Carmeuse_na.CLE",
    "N:\Carmeuse_na.IND",
    "N:\Case_western.CLE",
    "N:\Cf_ind_nitrogen.CHI",
    "N:\Charter Steel",
    "N:\Chemical_Design.BUF",
    "N:\Cleve-cliff-cff.ASH",
    "N:\Cleve-cliff-cff.CLE",
    "N:\Cleve-cliff-cff.IND",
    "N:\Cleve-cliffs.ASH",
    "N:\CNX Resources Corp",
    "N:\Comm_metals.BUF",
    "N:\Complete Filtration Resources",
    "N:\Con_Edison.BUF",
    "N:\Consumers Energ.CHI",
    "N:\Corning.BUF",
    "N:\Corteva Agrisciences",
    "N:\Creative Werks",
    "N:\Croda Inc",
    "N:\Csm_group_inc.CHI",
    "N:\Cuyahoga_county.CLE",
    "N:\Dairy Farmers of America",
    "N:\Dairyland_power.CHI",
    "N:\Danieli Corp",
    "N:\Danone",
    "N:\DCP Midstream",
    "N:\DfsrPrivate",
    "N:\Diageo",
    "N:\Don_Hall_SC.ASH",
    "N:\DTE_Energy",
    "N:\Dte_energy.CLE",
    "N:\DuPont_Nutrition&Health",
    "N:\Duqesne_Light.CLE",
    "N:\Dynamix_eng.CHI",
    "N:\Dynegy.CHI",
    "N:\Dynegy.CLE",
    "N:\Eco-Energy_llc.ASH",
    "N:\Elementis.CLE",
    "N:\Emergent_Bio.CHI",
    "N:\Enerfab_Inc.MAD",
    "N:\Energy Transfer",
    "N:\Energy_Harbor.CLE",
    "N:\EQT Corp",
    "N:\EQUISTAR.CHI",
    "N:\Equitrans Midstream",
    "N:\Ergon West Virginia",
    "N:\Eversource.MAD",
    "N:\Evonik_degussa.CHI",
    "N:\Evonik_degussa.TOL",
    "N:\Exelon_Power.CLE",
    "N:\Exxonmob_upstrm.CLE",
    "N:\Exxonmobil.CHI",
    "N:\Ferguson Electric",
    "N:\Ferro_corp.CLE",
    "N:\FH Paschen",
    "N:\Firstenergyserv.CLE",
    "N:\Firstenergyserv.MAD",
    "N:\FIRSTENR.CLE",
    "N:\Franklin_Ind.CLE",
    "N:\Fufeng_USA_inc.CHI",
    "N:\Gen_svc_admin.CHI",
    "N:\General Electric Vernova",
    "N:\Glanbia",
    "N:\GOJO_Industries.CLE",
    "N:\Griffith Foods.CHI",
    "N:\Haldor_topsoe.CHI",
    "N:\Harper_int.BUF",
    "N:\Hauhinco.CLE - Copy",
    "N:\Haverhill_chem.ASH",
    "N:\Henkel_corp.CHI",
    "N:\Hershey.CHI",
    "N:\Holland_LP.BUF",
    "N:\Holland_LP.CHI",
    "N:\HP_Hood_LLC.CHI",
    "N:\Hydro-Thermal.CHI",
    "N:\Hyosung Corp",
    "N:\IHI Power Services Corp",
    "N:\IHI Power.MAD",
    "N:\Illinois_state.CHI",
    "N:\Indiana_univ.CHI",
    "N:\Ineos.CLE",
    "N:\Ineos_joliet_ll.CHI",
    "N:\Ineos_styrenics.CHI",
    "N:\Infineum",
    "N:\Instant_Access.CHI",
    "N:\Interactive_D_A.CHI",
    "N:\InterMat_LLC.CLE",
    "N:\InterstatePower.CHI",
    "N:\Italmatch_Chem.CHI",
    "N:\JJHenderson&Son.CHI",
    "N:\Jsw_steel.BUF",
    "N:\JSW2305",
    "N:\Kettle Cuisine",
    "N:\Key West Metal.CHI",
    "N:\Kiewit_corp.CHI",
    "N:\Kikkoman Foods.CHI",
    "N:\Kinder Morgan",
    "N:\Koppers_inc.CHI",
    "N:\Kraft Heinz.CHI",
    "N:\Li-Cycle.BUF",
    "N:\Louis_Drefus.CHI",
    "N:\LUBRIZOL.CLE",
    "N:\Madison_gas_ele.CHI",
    "N:\Magnum_Hunter.ASH",
    "N:\Map_Detroit.ASH",
    "N:\MARATHON.CHI",
    "N:\Marathon_Mandan.ASH",
    "N:\Markwest_utica.CLE",
    "N:\Mascaro Construction Co",
    "N:\Mbl_USA_corp.CHI",
    "N:\McCain Foods",
    "N:\Mccormick.CHI",
    "N:\Meijer.CLE",
    "N:\Merck_and_co.CHI",
    "N:\Messer_ind.CHI",
    "N:\Metallus Inc",
    "N:\Middough.ASH",
    "N:\Middough.CHI",
    "N:\Middough.IND",
    "N:\Middough.TOL",
    "N:\Mittal.BUF",
    "N:\Mittal.CLE",
    "N:\Nanophase_techn.CHI",
    "N:\National_grid.BUF",
    "N:\Nature's_Fynd.CHI",
    "N:\Ne_illinois_unv.CHI",
    "N:\Nestle Purina Petcare",
    "N:\Nestle.chi",
    "N:\Nestle.CLE",
    "N:\Nidec.CLE",
    "N:\Nisource.CHI",
    "N:\Nisource.IND",
    "N:\Nlmk_USA.CLE",
    "N:\North_Chicago.CHI",
    "N:\Northstar_Med.CHI",
    "N:\Northstar_med.MAD",
    "N:\Novonesis",
    "N:\Now_Foods.CHI",
    "N:\Nrg_energy.BUF",
    "N:\NRG_energy.CHI",
    "N:\NRG_energy.MAD",
    "N:\Nucor Corporation",
    "N:\Nucor.CLE",
    "N:\Nyserda.BUF",
    "N:\Occidental_chem.BUF",
    "N:\Occidental_chem.IND",
    "N:\Oh_fac_const_co.CLE",
    "N:\Oil-Dri Corp",
    "N:\Olam Group",
    "N:\Olin_chlor.BUF",
    "N:\Osi.CHI",
    "N:\Ozinga Concrete.BUF",
    "N:\Panda_restauran.CHI",
    "N:\Paul_wurth_inc.BUF",
    "N:\Phibro Animal Health",
    "N:\Plum_Point_Serv.CHI",
    "N:\Plum_point_serv.MAD",
    "N:\Post Consumer Brands",
    "N:\Prairie_state.CHI",
    "N:\PRAXAIR.CLE",
    "N:\Prec_Survey.IND",
    "N:\Pro_unlimited.BUF",
    "N:\Rabco_Energy.CHI",
    "N:\Rep.CLE",
    "N:\Rich Products Co",
    "N:\Rockfor_gen_llc.MAD",
    "N:\Ross_incinerati.CLE",
    "N:\Ross_products.CHI",
    "N:\Royal_Chemical.CLE",
    "N:\Schenck_process.CHI",
    "N:\Seadrift.PWOL",
    "N:\Seadrift_coke.CHI",
    "N:\Sms_meer_svcs.BUF",
    "N:\Solvay.CLE",
    "N:\Solvay.IND",
    "N:\South Central Power",
    "N:\Staples_inc.CHI",
    "N:\Starcon_intl.CHI",
    "N:\Starcon_intl.CLE",
    "N:\Stelco Inc.BUF",
    "N:\StPaul MAM",
    "N:\Sun_chem_ink.CHI",
    "N:\Sun_coke_co.ASH",
    "N:\Sun_coke_energy.BUF",
    "N:\Sun_coke_energy.CHI",
    "N:\SUNCHEM.CLE",
    "N:\SunChemical.chi",
    "N:\Suncor_energy.CHI",
    "N:\Sunoco.CHI",
    "N:\Sunoco_Inc.ash",
    "N:\Synata_Bio_inc.CHI",
    "N:\Synthomer_Plc.CLE",
    "N:\Sysmex_Reagents.CHI",
    "N:\Tata_Steel.CLE",
    "N:\TCE Energy",
    "N:\Techint_eng.CLE",
    "N:\Ternium",
    "N:\The_Andersons.CHI",
    "N:\TMS International",
    "N:\Trachte_llc.MAD",
    "N:\Tronox_limited.CLE",
    "N:\UGI Energy",
    "N:\United_st_steel.BUF",
    "N:\United_st_steel.CLE",
    "N:\Univ_illinois.MAD",
    "N:\Univ_wisconsin.CHI",
    "N:\Univ_wisconsin.MAD",
    "N:\Universal_stain.PIT",
    "N:\V&m_star.CLE",
    "N:\Valero_memphis.CHI",
    "N:\Valspar_corp.CHI",
    "N:\Vinland_energy.ASH",
    "N:\Vistra_Energy.CLE",
    "N:\Wacker_chem.CHI",
    "N:\Wellpet_LLC.CHI",
    "N:\Wisconsin_admin.MAD",
    "N:\Wolverine_Power.CLE"
)
    #>

#2nd run
$folders = @(
    "N:\Anheuser_Busch.CHI",
    "N:\Applied Metals.CLE",
    "N:\Arcelor_mittal.CHI",
    "N:\Army_contract.CHI",
    "N:\Ashland_chemical.ASH",
    "N:\Atlantic_Power.CHI",
    "N:\Aurubis.BUF",
    "N:\Aux_sable.CHI",
    "N:\Avery_dennison.CLE",
    "N:\AveXis_inc.CHI",
    "N:\B&G Foods.CHI",
    "N:\Baker_petrolite.CHI",
    "N:\Barry_Callebaut.CHI",
    "N:\Beyond_meat.CHI",
    "N:\Big_river_steel.CLE",
    "N:\Bio-Cat_Mico.CHI",
    "N:\Biourja.CHI",
    "N:\Blommer.CHI",
    "N:\Boyd_CY_Court.ASH",
    "N:\BP_OIL.CLE",
    "N:\Bp_research.CHI",
    "N:\Brandenburg_Ind.CHI",
    "N:\Brightmark_Eng",
    "N:\Bunge North Ame.CHI",
    "N:\BWX_Tech.CLE",
    "N:\Capchem Technology USA",
    "N:\Carmeuse_na.CLE",
    "N:\Carmeuse_na.IND",
    "N:\Case_western.CLE",
    "N:\Cf_ind_nitrogen.CHI",
    "N:\Chemical_Design.BUF",
    "N:\Cleve-cliff-cff.ASH",
    "N:\Cleve-cliff-cff.CLE",
    "N:\Cleve-cliff-cff.IND",
    "N:\Cleve-cliffs.ASH",
    "N:\Comm_metals.BUF",
    "N:\Complete Filtration Resources",
    "N:\Con_Edison.BUF",
    "N:\Consumers Energ.CHI",
    "N:\Corning.BUF",
    "N:\Csm_group_inc.CHI",
    "N:\Cuyahoga_county.CLE",
    "N:\Dairyland_power.CHI",
    "N:\DCP Midstream",
    "N:\Don_Hall_SC.ASH",
    "N:\Dte_energy.CLE",
    "N:\DTE_Energy",
    "N:\DuPont_Nutrition&Health",
    "N:\Duqesne_Light.CLE",
    "N:\Dynamix_eng.CHI",
    "N:\Dynegy.CHI",
    "N:\Dynegy.CLE",
    "N:\Eco-Energy_llc.ASH",
    "N:\Elementis.CLE",
    "N:\Emergent_Bio.CHI",
    "N:\Enerfab_Inc.MAD",
    "N:\Energy Transfer",
    "N:\Energy_Harbor.CLE",
    "N:\EQT Corp",
    "N:\EQUISTAR.CHI",
    "N:\Equitrans Midstream",
    "N:\Eversource.MAD",
    "N:\Evonik_degussa.CHI",
    "N:\Evonik_degussa.TOL",
    "N:\Exelon_Power.CLE",
    "N:\Exxonmob_upstrm.CLE",
    "N:\Exxonmobil.CHI",
    "N:\Ferro_corp.CLE",
    "N:\FH Paschen",
    "N:\Firstenergyserv.CLE",
    "N:\Firstenergyserv.MAD",
    "N:\FIRSTENR.CLE",
    "N:\Franklin_Ind.CLE",
    "N:\Fufeng_USA_inc.CHI",
    "N:\Gen_svc_admin.CHI",
    "N:\General Electric Vernova",
    "N:\GOJO_Industries.CLE",
    "N:\Griffith Foods.CHI",
    "N:\Haldor_topsoe.CHI",
    "N:\Harper_int.BUF",
    "N:\Hauhinco.CLE - Copy",
    "N:\Haverhill_chem.ASH",
    "N:\Henkel_corp.CHI",
    "N:\Hershey.CHI",
    "N:\Holland_LP.BUF",
    "N:\Holland_LP.CHI",
    "N:\HP_Hood_LLC.CHI",
    "N:\Hydro-Thermal.CHI",
    "N:\Hyosung Corp",
    "N:\IHI Power Services Corp",
    "N:\IHI Power.MAD",
    "N:\Illinois_state.CHI",
    "N:\Indiana_univ.CHI",
    "N:\Ineos.CLE",
    "N:\Ineos_joliet_ll.CHI",
    "N:\Ineos_styrenics.CHI",
    "N:\Infineum",
    "N:\Instant_Access.CHI",
    "N:\Interactive_D_A.CHI",
    "N:\InterMat_LLC.CLE",
    "N:\InterstatePower.CHI",
    "N:\Italmatch_Chem.CHI",
    "N:\JJHenderson&Son.CHI",
    "N:\Jsw_steel.BUF",
    "N:\Key West Metal.CHI",
    "N:\Kiewit_corp.CHI",
    "N:\Kikkoman Foods.CHI",
    "N:\Kinder Morgan",
    "N:\Koppers_inc.CHI",
    "N:\Kraft Heinz.CHI",
    "N:\Li-Cycle.BUF",
    "N:\Louis_Drefus.CHI",
    "N:\LUBRIZOL.CLE",
    "N:\Madison_gas_ele.CHI",
    "N:\Magnum_Hunter.ASH",
    "N:\Map_Detroit.ASH",
    "N:\MARATHON.CHI",
    "N:\Marathon_Mandan.ASH",
    "N:\Markwest_utica.CLE",
    "N:\Mbl_USA_corp.CHI",
    "N:\Mccormick.CHI",
    "N:\Meijer.CLE",
    "N:\Merck_and_co.CHI",
    "N:\Messer_ind.CHI",
    "N:\Metallus Inc",
    "N:\Middough.ASH",
    "N:\Middough.CHI",
    "N:\Middough.IND",
    "N:\Middough.TOL",
    "N:\Mittal.BUF",
    "N:\Mittal.CLE",
    "N:\Nanophase_techn.CHI",
    "N:\National_grid.BUF",
    "N:\Nature's_Fynd.CHI",
    "N:\Ne_illinois_unv.CHI",
    "N:\Nestle.chi",
    "N:\Nestle.CLE",
    "N:\Nidec.CLE",
    "N:\Nisource.CHI",
    "N:\Nisource.IND",
    "N:\Nlmk_USA.CLE",
    "N:\North_Chicago.CHI",
    "N:\Northstar_Med.CHI",
    "N:\Northstar_med.MAD",
    "N:\Novonesis",
    "N:\Now_Foods.CHI",
    "N:\Nrg_energy.BUF",
    "N:\NRG_energy.CHI",
    "N:\NRG_energy.MAD",
    "N:\Nucor.CLE",
    "N:\Nyserda.BUF",
    "N:\Occidental_chem.BUF",
    "N:\Occidental_chem.IND",
    "N:\Oh_fac_const_co.CLE",
    "N:\Olin_chlor.BUF",
    "N:\Osi.CHI",
    "N:\Ozinga Concrete.BUF",
    "N:\Panda_restauran.CHI",
    "N:\Paul_wurth_inc.BUF",
    "N:\Plum_Point_Serv.CHI",
    "N:\Plum_point_serv.MAD",
    "N:\Post Consumer Brands",
    "N:\Prairie_state.CHI",
    "N:\PRAXAIR.CLE",
    "N:\Prec_Survey.IND",
    "N:\Pro_unlimited.BUF",
    "N:\Rabco_Energy.CHI",
    "N:\Rep.CLE",
    "N:\Rich Products Co",
    "N:\Rockfor_gen_llc.MAD",
    "N:\Ross_incinerati.CLE",
    "N:\Royal_Chemical.CLE",
    "N:\Schenck_process.CHI",
    "N:\Seadrift_coke.CHI",
    "N:\Sms_meer_svcs.BUF",
    "N:\Solvay.CLE",
    "N:\Solvay.IND",
    "N:\South Central Power",
    "N:\Staples_inc.CHI",
    "N:\Starcon_intl.CHI",
    "N:\Starcon_intl.CLE",
    "N:\Stelco Inc.BUF",
    "N:\StPaul MAM",
    "N:\Sun_chem_ink.CHI",
    "N:\Sun_coke_co.ASH",
    "N:\Sun_coke_energy.BUF",
    "N:\Sun_coke_energy.CHI",
    "N:\SUNCHEM.CLE",
    "N:\SunChemical.chi",
    "N:\Suncor_energy.CHI",
    "N:\Sunoco.CHI",
    "N:\Sunoco_Inc.ash",
    "N:\Synata_Bio_inc.CHI",
    "N:\Synthomer_Plc.CLE",
    "N:\Sysmex_Reagents.CHI",
    "N:\Tata_Steel.CLE",
    "N:\TCE Energy",
    "N:\Techint_eng.CLE",
    "N:\3m.BUF",
    "N:\3m.CHI",
    "N:\Abbott.chi",
    "N:\Abbvie.CHI",
    "N:\AK_STEEL.ASH",
    "N:\Akzonoble.CHI",
    "N:\Altivia.ASH",
    "N:\Amer_elect_pwr.CLE",
    "N:\The_Andersons.CHI",
    "N:\TMS International",
    "N:\Trachte_llc.MAD",
    "N:\Tronox_limited.CLE",
    "N:\UGI Energy",
    "N:\United_st_steel.BUF",
    "N:\United_st_steel.CLE",
    "N:\Univ_illinois.MAD",
    "N:\Univ_wisconsin.CHI",
    "N:\Univ_wisconsin.MAD",
    "N:\Valspar_corp.CHI",
    "N:\Wellpet_LLC.CHI",
    "N:\Wolverine_Power.CLE"
)
$countdown = $folders.count
foreach ($folder in $folders) {
    Get-ChildItem $folder | Select-Object FullName | fl | Out-File -FilePath 'c:\temp\n drive folder size 012025.csv' -Append
    $totalSize = (Get-ChildItem -Recurse -Force $folder | Measure-Object -Property Length -Sum).Sum
    $totalSizeMB = [math]::Round($totalSize / 1MB, 2)
    "Total size for $folder : $totalSizeMB MB" | Out-File -FilePath 'c:\temp\n drive folder size 012025.csv' -Append
    $countdown--
    $countdown
}

# Create a new folder if it doesn't exist
$newFolderPath = "C:\temp\NewFolder"
if (-Not (Test-Path -Path $newFolderPath)) {
    New-Item -ItemType Directory -Path $newFolderPath
}


